"""tablas iniciales

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 19:30:45.821711
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contadores_uso',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sistema_id', sa.String(length=64), nullable=False),
    sa.Column('usuario_ref', sa.String(length=256), nullable=False),
    sa.Column('ventana', sa.String(length=8), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mensajes', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sistema_id', 'usuario_ref', 'ventana', 'inicio')
    )
    op.create_table('conversaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sistema_id', sa.String(length=64), nullable=False),
    sa.Column('usuario_ref', sa.String(length=256), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('creada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_sistema_usuario', 'conversaciones', ['sistema_id', 'usuario_ref', 'actualizada'], unique=False)
    op.create_table('llamadas_tool',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=True),
    sa.Column('sistema_id', sa.String(length=64), nullable=False),
    sa.Column('usuario_ref', sa.String(length=256), nullable=False),
    sa.Column('jti', sa.String(length=128), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('status_http', sa.Integer(), nullable=True),
    sa.Column('duracion_ms', sa.Integer(), nullable=True),
    sa.Column('bytes_respuesta', sa.Integer(), nullable=True),
    sa.Column('creada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llamada_sistema_usuario', 'llamadas_tool', ['sistema_id', 'usuario_ref', 'creada'], unique=False)
    op.create_index(op.f('ix_llamadas_tool_conversacion_id'), 'llamadas_tool', ['conversacion_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.String(length=16), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('modelo', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_conversacion_id'), 'mensajes', ['conversacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_conversacion_id'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_llamadas_tool_conversacion_id'), table_name='llamadas_tool')
    op.drop_index('ix_llamada_sistema_usuario', table_name='llamadas_tool')
    op.drop_table('llamadas_tool')
    op.drop_index('ix_conv_sistema_usuario', table_name='conversaciones')
    op.drop_table('conversaciones')
    op.drop_table('contadores_uso')
    # ### end Alembic commands ###
